// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type ExploreResponse struct {
	People []*Entity `json:"people"`
	Places []*Entity `json:"places"`
	Things []*Entity `json:"things"`
}
