// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AlbumConnection struct {
	Nodes      []*Album `json:"nodes"`
	TotalCount int      `json:"totalCount"`
}

type AutocompleteResponse struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateAlbumInput struct {
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	MediaItems  []*string `json:"mediaItems"`
}

type EntityItemConnection struct {
	Nodes      []*Entity `json:"nodes"`
	TotalCount int       `json:"totalCount"`
}

type ExploreResponse struct {
	People []*Entity `json:"people"`
	Places []*Entity `json:"places"`
	Things []*Entity `json:"things"`
}

type MediaItemConnection struct {
	Nodes      []*MediaItem `json:"nodes"`
	TotalCount int          `json:"totalCount"`
}

type UpdateAlbumInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
