db.entities.insertMany([
  { "name": "ANIMALS", "entityType": "things" },
  { "name": "FOOD", "entityType": "things" },
  { "name": "GARDENS", "entityType": "things" },
  { "name": "SPORT", "entityType": "things" },
  { "name": "PEOPLE", "entityType": "things" },
  { "name": "TRAVEL", "entityType": "things" },
  { "name": "WEDDINGS", "entityType": "things" },
  { "name": "LANDSCAPES", "entityType": "things" },
  { "name": "SCREENSHOTS", "entityType": "things" },
  { "name": "WHITEBOARDS", "entityType": "things" },
  { "name": "BIRTHDAYS", "entityType": "things" },
  { "name": "NIGHT", "entityType": "things" },
  { "name": "FLOWERS", "entityType": "things" },
  { "name": "SELFIES", "entityType": "things" },
  { "name": "CITYSCAPES", "entityType": "things" },
  { "name": "ARTS", "entityType": "things" },
  { "name": "CRAFTS", "entityType": "things" },
  { "name": "HOLIDAYS", "entityType": "things" },
  { "name": "FASHION", "entityType": "things" },
  { "name": "LANDMARKS", "entityType": "things" },
  { "name": "PERFORMANCES", "entityType": "things" },
  { "name": "RECEIPTS", "entityType": "things" },
  { "name": "DOCUMENTS", "entityType": "things" },
  { "name": "HOUSES", "entityType": "things" },
  { "name": "PETS", "entityType": "things" },
  { "name": "UTILITY", "entityType": "things" }
])