run:
  skip-dirs:
   - internal/graph/generated
linters:
  enable-all: true
  disable:
   - whitespace
   - godot
   - wrapcheck
   - gofumpt
   - gci
   - exhaustivestruct
   - dupl
   - funlen
   - cyclop
   - varnamelen
   - ireturn
linters-settings:
  lll:
    line-length: 140
    tab-width: 2
